# Generated by Django 3.2.9 on 2021-12-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreYApellido', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=40)),
                ('numeroDeTelefono', models.IntegerField()),
            ],
        ),
    ]
